# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../rpi-brew-gui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 389)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(2, 10, 641, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tTime = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tTime.sizePolicy().hasHeightForWidth())
        self.tTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.tTime.setFont(font)
        self.tTime.setStyleSheet("color: rgb(85, 87, 83);")
        self.tTime.setAlignment(QtCore.Qt.AlignCenter)
        self.tTime.setObjectName("tTime")
        self.verticalLayout.addWidget(self.tTime)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lBlue = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lBlue.setFont(font)
        self.lBlue.setStyleSheet("color: blue;")
        self.lBlue.setAlignment(QtCore.Qt.AlignCenter)
        self.lBlue.setObjectName("lBlue")
        self.gridLayout.addWidget(self.lBlue, 3, 1, 1, 1)
        self.tRedId = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tRedId.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tRedId.setBaseSize(QtCore.QSize(0, 0))
        self.tRedId.setStyleSheet("color: red;")
        self.tRedId.setMaxLength(6)
        self.tRedId.setAlignment(QtCore.Qt.AlignCenter)
        self.tRedId.setObjectName("tRedId")
        self.gridLayout.addWidget(self.tRedId, 0, 0, 1, 1)
        self.lRed = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lRed.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lRed.setFont(font)
        self.lRed.setAutoFillBackground(False)
        self.lRed.setStyleSheet("color: red;")
        self.lRed.setAlignment(QtCore.Qt.AlignCenter)
        self.lRed.setObjectName("lRed")
        self.gridLayout.addWidget(self.lRed, 3, 0, 1, 1)
        self.lGreen = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lGreen.setFont(font)
        self.lGreen.setStyleSheet("color: green;")
        self.lGreen.setAlignment(QtCore.Qt.AlignCenter)
        self.lGreen.setObjectName("lGreen")
        self.gridLayout.addWidget(self.lGreen, 3, 2, 1, 1)
        self.tBlueID = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tBlueID.setStyleSheet("color: blue;")
        self.tBlueID.setAlignment(QtCore.Qt.AlignCenter)
        self.tBlueID.setObjectName("tBlueID")
        self.gridLayout.addWidget(self.tBlueID, 0, 1, 1, 1)
        self.tGreenId = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tGreenId.setStyleSheet("color: green;")
        self.tGreenId.setAlignment(QtCore.Qt.AlignCenter)
        self.tGreenId.setObjectName("tGreenId")
        self.gridLayout.addWidget(self.tGreenId, 0, 2, 1, 1)
        self.lRedOK = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lRedOK.sizePolicy().hasHeightForWidth())
        self.lRedOK.setSizePolicy(sizePolicy)
        self.lRedOK.setAlignment(QtCore.Qt.AlignCenter)
        self.lRedOK.setObjectName("lRedOK")
        self.gridLayout.addWidget(self.lRedOK, 2, 0, 1, 1)
        self.lBlueOK = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lBlueOK.sizePolicy().hasHeightForWidth())
        self.lBlueOK.setSizePolicy(sizePolicy)
        self.lBlueOK.setAlignment(QtCore.Qt.AlignCenter)
        self.lBlueOK.setObjectName("lBlueOK")
        self.gridLayout.addWidget(self.lBlueOK, 2, 1, 1, 1)
        self.lGreenOK = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lGreenOK.sizePolicy().hasHeightForWidth())
        self.lGreenOK.setSizePolicy(sizePolicy)
        self.lGreenOK.setAlignment(QtCore.Qt.AlignCenter)
        self.lGreenOK.setObjectName("lGreenOK")
        self.gridLayout.addWidget(self.lGreenOK, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RPI Brew v0.1"))
        self.tTime.setText(_translate("MainWindow", "00:00"))
        self.lBlue.setText(_translate("MainWindow", "###.# °C"))
        self.tRedId.setPlaceholderText(_translate("MainWindow", "Sensor ID"))
        self.lRed.setText(_translate("MainWindow", "###.# °C"))
        self.lGreen.setText(_translate("MainWindow", "###.# °C"))
        self.tBlueID.setPlaceholderText(_translate("MainWindow", "Sensor ID"))
        self.tGreenId.setPlaceholderText(_translate("MainWindow", "Sensor ID"))
        self.lRedOK.setText(_translate("MainWindow", "NOK"))
        self.lBlueOK.setText(_translate("MainWindow", "NOK"))
        self.lGreenOK.setText(_translate("MainWindow", "NOK"))

